/*
 Navicat Premium Data Transfer

 Source Server         : server_recuperi_NOVPN
 Source Server Type    : MySQL
 Source Server Version : 100215
 Source Host           : 192.168.1.220:4081
 Source Schema         : federicodb

 Target Server Type    : MySQL
 Target Server Version : 100215
 File Encoding         : 65001

 Date: 21/05/2026 09:37:30
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for mcrecorecuallepubb
-- ----------------------------
DROP TABLE IF EXISTS `mcrecorecuallepubb`;
CREATE TABLE `mcrecorecuallepubb`  (
  `MCRECA_PK` int NOT NULL AUTO_INCREMENT,
  `MCRECA_EST_COA` varchar(20) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECA_AR1_FL_DAT` date NOT NULL DEFAULT '0001-01-01',
  `MCRECA_IM3_COA` varchar(20) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECA_FIR_FLG` tinyint NOT NULL DEFAULT 0,
  `MCRECA_OPR_EK` int NOT NULL DEFAULT 0,
  `MCRECA_DESC_DSL` varchar(250) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECA_DOCPR_FLG` tinyint NOT NULL DEFAULT 0,
  `MCRECA_PROC_ACR` char(2) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT '',
  `MCRECA_PBU_NUM` int NOT NULL DEFAULT 0,
  `MCRECA_PBU_ANN` smallint NOT NULL DEFAULT 0,
  `MCRECA_PERCAL_DES` varchar(200) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECA_DOC_BLB` longblob NULL,
  `MCRECA_REC_FLG` tinyint NOT NULL DEFAULT 0,
  `MCRECA_TIP_FLG` tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (`MCRECA_PK`) USING BTREE
) ENGINE = MyISAM AUTO_INCREMENT = 4135 AVG_ROW_LENGTH = 100000 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci MAX_ROWS = 1000000000 ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for mcputerecupubbinte
-- ----------------------------
DROP TABLE IF EXISTS `mcputerecupubbinte`;
CREATE TABLE `mcputerecupubbinte`  (
  `MCRECU_PK` int NOT NULL AUTO_INCREMENT,
  `MCRECU_PR6_ANN` smallint NOT NULL DEFAULT 0,
  `MCRECU_ARE_FK` int NOT NULL DEFAULT 0,
  `MCRECU_PR6_DAT` date NOT NULL DEFAULT '0001-01-01',
  `MCRECU_OGG_NTC` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `MCRECU_ATT_DAT` date NOT NULL DEFAULT '0001-01-01',
  `MCRECU_ATT_INT_COA` varchar(20) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECU_PR6_MIT_COA` varchar(20) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECU_ATT_EST_COA` varchar(20) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECU_NUM_PR6_COA` varchar(20) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECU_ATT_INT_ANN` smallint NOT NULL DEFAULT 0,
  `MCRECU_GNR_NUM` bigint NOT NULL DEFAULT 0,
  `MCRECU_PBU_ANN` smallint NOT NULL DEFAULT 0,
  `MCRECU_PBU_NUM` int NOT NULL DEFAULT 0,
  `MCRECU_PBU_DAT` date NOT NULL DEFAULT '0001-01-01',
  `MCRECU_INZ_DAT` date NOT NULL DEFAULT '0001-01-01',
  `MCRECU_FIN_DAT` date NOT NULL DEFAULT '0001-01-01',
  `MCRECU_SCD_DAT` date NOT NULL DEFAULT '0001-01-01',
  `MCRECU_RST_DAT` date NOT NULL DEFAULT '0001-01-01',
  `MCRECU_LV3_DAT` date NOT NULL DEFAULT '0001-01-01',
  `MCRECU_ST9_FK` int NOT NULL DEFAULT 0,
  `MCRECU_OPR_EK` int NOT NULL DEFAULT 0,
  `MCRECU_PBU_NTC` varchar(250) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECU_OP9_FLG` tinyint NOT NULL DEFAULT 0,
  `MCRECU_RELA_FK` int NOT NULL DEFAULT 0,
  `MCRECU_ID1_BLB_NUM` bigint NOT NULL DEFAULT 0,
  `MCRECU_EST_COA` varchar(20) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECU_STO_FLG` tinyint NOT NULL DEFAULT 0,
  `MCRECU_INZ2_DAT` date NOT NULL DEFAULT '0001-01-01',
  `MCRECU_FIN2_DAT` date NOT NULL DEFAULT '0001-01-01',
  `MCRECU_OPEPU_EK` int NOT NULL DEFAULT 0,
  `MCRECU_RCP_FLG` tinyint NOT NULL DEFAULT 0,
  `MCRECU_LUOG_DES` varchar(50) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECU_ANR_NOM` varchar(60) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECU_ANR_COG` varchar(60) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECU_ANR_RAG` varchar(100) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECU_ANR_CF` varchar(16) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECU_ANR_PI` varchar(11) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECU_ANRNAS_DAT` date NOT NULL DEFAULT '0001-01-01',
  `MCRECU_ANRIND_COA` varchar(80) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECU_ANRCTT_COA` varchar(50) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECU_TPATT_DES` varchar(50) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECU_RESTI_NOM` varchar(60) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECU_RESTI_COG` varchar(60) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECU_RESTI_CF` varchar(16) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECU_RESTI_PI` varchar(11) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECU_RESTI_RAG` varchar(100) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECU_RESTCTT_COA` varchar(20) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECU_RESTIND_COA` varchar(20) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECU_RESTNAS_DAT` date NOT NULL DEFAULT '0001-01-01',
  `MCRECU_UNOR_DES` varchar(50) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECURESCNM` varchar(120) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCRECU_MTT_FK` int NOT NULL DEFAULT 0,
  `MCRECU_RST_FK` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`MCRECU_PK`) USING BTREE
) ENGINE = MyISAM AUTO_INCREMENT = 3423 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for mcreterecuanag
-- ----------------------------
DROP TABLE IF EXISTS `mcreterecuanag`;
CREATE TABLE `mcreterecuanag`  (
  `MCREA_PK` int NOT NULL AUTO_INCREMENT,
  `MCREA_ANR_NOM` varchar(60) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCREA_ANR_COG` varchar(60) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCREA_ANR_RAG` varchar(100) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCREA_NSC_DAT` date NOT NULL DEFAULT '0001-01-01',
  `MCREA_ANR_CF` varchar(16) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCREA_ANR_PI` varchar(11) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCREA_IND_COA` varchar(80) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  `MCREA_CTT_COA` varchar(50) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT ' ',
  PRIMARY KEY (`MCREA_PK`) USING BTREE
) ENGINE = MyISAM AUTO_INCREMENT = 3 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
